version: '2.0'
services:
    shinynbis:
        image: nanjiang/shinynbis
        container_name: shinynbis
        volumes:
            - /srv/shiny-server:/srv/shiny-server
            - /srv/shinylog:/var/log/shiny-server
            - /media/storage:/media/storage
        ports:
            - "80:3838"
        restart: always
        stdin_open: true
        tty: true

