version: "2"

services:

######################### SETUP OF PROXY AND SSL ###############################
# The following set up is taken from encrypted_dashboard developed by
# mikkelkrogsholm and lstmemery
# Gitrepo: https://github.com/mikkelkrogsholm/encrypted_dashboard

# Don't edit this service
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

# Don't edit this service
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    depends_on:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

# Don't edit this service
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
      - nginx-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

####################### SETUP OF DOCKER CONTAINERS #############################

# Spin up a Shiny docker
  shinymain:
      restart: always
      image: nanjiang/shinynbis 
      container_name: shinymain
      expose:
        - "3838"
      environment:
        - VIRTUAL_HOST=rshiny.nbis.se # change line
        - VIRTUAL_NETWORK=nginx-proxy # change line
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=rshiny.nbis.se # change line
        - LETSENCRYPT_EMAIL=nanjiang.shu@nbis.se # change line
      volumes:
        - ./web:/srv/shiny-server
        - ${PATH_APPS}:/srv/shiny-server/shiny-server-apps
        - ./shiny-server-conf/shiny-server-main.conf:/etc/shiny-server/shiny-server.conf
        - ./volumes/shiny/logs:/var/log/

  shinymetamex:
      restart: always
      image: nanjiang/shinynbis 
      container_name: shinymetamex
      expose:
        - "3838"
      environment:
        - VIRTUAL_HOST=www.metamex.eu # change line
        - VIRTUAL_NETWORK=nginx-proxy # change line
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=www.metamex.eu # change line
        - LETSENCRYPT_EMAIL=nanjiang.shu@nbis.se # change line
      volumes:
        - ${PATH_APPS_METAMEX}:/srv/shiny-server/MetaMEx
        - ./shiny-server-conf/shiny-server-metamex.conf:/etc/shiny-server/shiny-server.conf
        - ./volumes/shiny/logs:/var/log/

# Watchtower is a process for watching your Docker containers and automatically
# updating and restarting them whenever their base image is refreshed.
  watchtower:
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    # Look for new images every midnight and Removes old images
    command: --schedule "0 0 0 *" --cleanup

