version: '2.0'
services:
    shinynbis:
        image: nanjiang/shinynbis
        container_name: shinynbis
        volumes:
            - ${PATH_APPS}:/srv/shiny-server/shiny-server-apps
        ports:
            - "80:3838"
        restart: always
        stdin_open: true
        tty: true

